import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("telecom_kpi.csv")
print(df.head())
print(df.info())
print(df.shape)
df["Timestamp"]=pd.to_datetime(df["Timestamp"])
print(df.dtypes)
df=df.sort_values(by="Timestamp")
df.reset_index(drop=True, inplace=True)
print("\nDataset Sorted Successfully")
missing_timestamp_summary = {}
for cell in df["Cell_ID"].unique():
    cell_df = df[df["Cell_ID"] == cell]
    expected = pd.date_range(start=cell_df["Timestamp"].min(),end=cell_df["Timestamp"].max(),freq="5min")
    missing = expected.difference(cell_df["Timestamp"])
    missing_timestamp_summary[cell] = len(missing)
print("\nMissing Timestamps Per Cell")
print(missing_timestamp_summary)
print(df.isnull().sum())
daily = (df.groupby(df["Timestamp"].dt.date).mean(numeric_only=True))
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["Throughput"],marker="o")
plt.title("Daily Average Throughput")
plt.xlabel("Date")
plt.ylabel("Throughput (Mbps)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["Latency"],marker="o")
plt.title("Daily Average Latency")
plt.xlabel("Date")
plt.ylabel("Latency (ms)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["SINR"],marker="o")
plt.title("Daily Average SINR")
plt.xlabel("Date")
plt.ylabel("SINR (dB)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["RSRP"],marker="o")
plt.title("Daily Average RSRP")
plt.xlabel("Date")
plt.ylabel("RSRP (dBm)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["Packet_Loss"],marker="o")
plt.title("Daily Average Packet Loss")
plt.xlabel("Date")
plt.ylabel("Packet Loss (%)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,5))
plt.plot(daily.index,daily["Connected_Users"],marker="o")
plt.title("Daily Average Connected Users")
plt.xlabel("Date")
plt.ylabel("Connected Users")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
weekly=df.set_index("Timestamp").resample("W").mean(numeric_only=True)
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["Throughput"], marker="o")
plt.title("Weekly Average Throughput")
plt.xlabel("Week")
plt.ylabel("Throughput (Mbps)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["Latency"], marker="o")
plt.title("Weekly Average Latency")
plt.xlabel("Week")
plt.ylabel("Latency (ms)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["SINR"], marker="o")
plt.title("Weekly Average SINR")
plt.xlabel("Week")
plt.ylabel("SINR (dB)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["RSRP"], marker="o")
plt.title("Weekly Average RSRP")
plt.xlabel("Week")
plt.ylabel("RSRP (dBm)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["Packet_Loss"], marker="o")
plt.title("Weekly Average Packet Loss")
plt.xlabel("Week")
plt.ylabel("Packet Loss (%)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
plt.plot(weekly.index, weekly["Connected_Users"], marker="o")
plt.title("Weekly Average Connected Users")
plt.xlabel("Week")
plt.ylabel("Users")
plt.grid(True)
plt.tight_layout()
plt.show()
print("\nStatistical Summary")
print(df.describe())