import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("telecom_kpi.csv")
df["Timestamp"]=pd.to_datetime(df["Timestamp"])
df=df.sort_values(by="Timestamp")
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["Throughput"])
plt.title("Throughput Over Time")
plt.xlabel("Timestamp")
plt.ylabel("Throughput (Mbps)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["Latency"])
plt.title("Latency Over Time")
plt.xlabel("Timestamp")
plt.ylabel("Latency (ms)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["SINR"])
plt.title("SINR Trend")
plt.xlabel("Timestamp")
plt.ylabel("SINR (dB)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["RSRP"])
plt.title("RSRP Trend")
plt.xlabel("Timestamp")
plt.ylabel("RSRP (dBm)")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["Packet_Loss"])
plt.title("Packet Loss Trend")
plt.xlabel("Timestamp")
plt.ylabel("Packet Loss")
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.plot(df["Timestamp"], df["Connected_Users"])
plt.title("Connected Users Trend")
plt.xlabel("Timestamp")
plt.ylabel("Connected Users")
plt.grid(True)
plt.tight_layout()
plt.show()
daily =(df.groupby(df["Timestamp"].dt.date).mean(numeric_only=True))
kpis=["Throughput","Latency","RSRP","SINR","Packet_Loss","Connected_Users"]
for kpi in kpis:
    plt.figure(figsize=(12,5))
    plt.plot(daily.index,daily[kpi],marker="o")
    plt.title(f"Daily Average {kpi}")
    plt.xlabel("Date")
    plt.ylabel(kpi)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.show()
hourly =(df.groupby(df["Timestamp"].dt.hour).mean(numeric_only=True))
plt.figure(figsize=(10,5))
plt.plot(hourly.index,hourly["Connected_Users"],marker="o",linewidth=2)
plt.title("Hourly Traffic Pattern")
plt.xlabel("Hour of the day")
plt.ylabel("Average Connected Users")
plt.xticks(range(24))
plt.grid(True)
plt.tight_layout()
plt.show()
weekly=df.set_index("Timestamp").resample("W").mean(numeric_only=True)
plt.figure(figsize=(10,5))
plt.plot(weekly.index,weekly["Connected_Users"],marker="o",linewidth=2)
plt.title("Weekly Traffic Comparision")
plt.xlabel("Week")
plt.ylabel("Average Connected Users")
plt.grid(True)
plt.tight_layout()
plt.show()